feat: ガイド記事一覧機能の追加
zenn-dev/zenn-vscode-extension pull request #59
Opened 2023-02-01 10:22 UTC by yo-goto

## :bookmark_tabs: Summary

ガイド記事一覧の機能を追加しました。
- ガイドを開くための「Zenn: Open Guide」コマンドを実装しました
  - コマンドパレットから実行した場合にはガイド記事を選択するプロンプトが表示されます
- TreeView に GUIDES セクションを追加し、ボタンクリックによって Zenn.dev 上のガイド記事にアクセスできるようにしました
  - zenn-cli で表示される各ガイド記事の絵文字とベータ版の表示を一致させました

コマンドパレットからの実行 | ガイドパネルの表示
--|--
![コマンドパレットからの実行](https://user-images.githubusercontent.com/50942816/216015839-7152ec37-3472-4501-b82c-28546ecbfd63.jpg) | ![ガイドのサイドパネルの子要素部分にボタンがあります](https://user-images.githubusercontent.com/50942816/216012827-6c04d733-fff7-4935-8744-89a16c509834.jpg)

Resolves #55 

### :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [ ] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-vscode-extension/blob/main/CONTRIBUTING.md) を読んだ
- [ ] :woman_technologist: `canary` ブランチに対するプルリクエストである
- [ ] 実行して正しく動作しているか確認する
- [ ] 不要なコードが含まれていないか( コメントやログの消し忘れに注意 )
- [ ] XSS になるようなコードが含まれていないか
- [ ] Pull Reuqest の内容は妥当か( 膨らみすぎてないか )

より詳しい内容は [Pull Request Policy](https://github.com/zenn-dev/zenn-vscode-extension/blob/main/docs/pull_request_policy.md) を参照してください。

2023-02-01 11:00 UTC, yo-goto commented
少しだけコードの整理を行いました。後の変更点は無いです。

2023-02-01 16:02 UTC, yo-goto commented
撤回します🙇‍♂️記事タイトルが気になったのでそこだけ修正して、ドキュメント内に挿入する画像を他の画像と同じように作り直しました。
![ガイドのサイドパネルの子要素部分にボタンがあります](https://user-images.githubusercontent.com/50942816/216094321-ef951df3-5dea-4a3d-82c6-f3b4c8a387d1.jpg)

2023-02-02 03:34 UTC, uttk-dev requested changes
@yo-goto 

PR ありがとうございます！
全体的によく作られていて、しかも README もちゃんと書かれていて感動しました👍
いくつか気になったところがあったので、コメントしました！
確認のほど、よろしくお願いします🙏

2023-02-02 03:34 UTC, uttk-dev commented on src/commands/openGuide.ts
> +    if (!context) throw new Error("コマンドを実行できません");
ここは throw するよりも `vscode.window.showErrorMessage` を使った方がいいかなと思いました。

```suggestion
    if (!context) `vscode.window.showErrorMessage("コマンドに失敗しました")`
```

2023-02-02 03:34 UTC, uttk-dev commented on src/variables.ts
> +};
`apiRoot` は使ってなさそうなので、混乱を避けるためにも削除した方がいいかなと思いました。
修正するなら以下のような感じですかね 👇

```suggestion
export const GUIDE_DOCS_BASE_URL = "https://zenn.dev/zenn/articles/"
```

2023-02-02 03:34 UTC, uttk-dev commented on src/treeview/guide/guideTreeViewProvider.ts
> +  }
ここの `this.guideDocsMetaData` は他で加工処理などしてなさそうなので、この変数を定義せずに `GUIDE_DOCS_META_DATA` をそのまま使う感じでいいかなと思いました。

2023-02-02 03:34 UTC, uttk-dev commented on src/treeview/guide/guideTreeViewProvider.ts
> +    );
上記のレビューを受け入れるなら、`GUIDE_DOCS_META_DATA` を使うようにしていただいて、`result` だと意味が伝わりづらいと思ったので、`metadata` ではどうでしょうか？

```suggestion
    const treeItems = GUIDE_DOCS_META_DATA.map(
      (metadata) => new GuideTreeItem(this.context, createGuideContent(metadata))
    );
```

2023-02-02 03:34 UTC, uttk-dev commented on src/variables.ts
> +  },
ソースコードを見やすくするために、URLエンコーディングされたモノではなく、そのまま日本語にしてみてはいかがでしょうか？

```suggestion
  {
    title: "記事の作成ガイド",
    slug: "zenn-cli-guide",
    hash: "cli-で記事（article）を管理する",
    emoji: "📝",
  },
  {
    title: "本の作成ガイド",
    slug: "zenn-cli-guide",
    hash: "cli-で本（book）を管理する",
    emoji: "📚",
  },
```

2023-02-02 08:52 UTC, yo-goto commented
レビューありがとうございます！
指摘箇所について見直して修正してみます！

2023-02-02 10:01 UTC, yo-goto commented on src/commands/openGuide.ts
> +    if (!context) throw new Error("コマンドを実行できません");
分かりました。ここはエラーメッセージ発生させて `false` を返すようにしてみます。
```suggestion
    if (!context) {
      vscode.window.showErrorMessage("コマンドに失敗しました");
      return false;
    }
```

2023-02-02 10:03 UTC, yo-goto commented on src/variables.ts
> +};
webview で使えるようにしていた利用していない部分がいくつかあったので、その箇所と同時にコードからいらない部分を削除しておきます。

2023-02-02 10:34 UTC, yo-goto commented
@uttk-dev 
修正完了致しました👍

2023-02-03 02:30 UTC, uttk-dev approved these changes
LGTMです！ありがとうございました！

2023-02-03 02:30 UTC, merged