feat: アクティブファイルのプレビュー機能の追加
zenn-dev/zenn-vscode-extension pull request #61
Opened 2023-02-03 10:06 UTC by yo-goto

## :bookmark_tabs: Summary

- 現在開いているマークダウンファイルが Zenn のリポジトリに存在している場合に、コマンドパレットからプレビューコマンド呼び出しでプレビューできる機能を追加しました
- 現在開いているファイルがマークダウンファイルならエディタタイトル上にプレビューコマンドのボタンが表示されるようにしました

Resolves #<issue-url>

### :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [x] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-vscode-extension/blob/main/CONTRIBUTING.md) を読んだ
- [x] :woman_technologist: `canary` ブランチに対するプルリクエストである
- [x] 実行して正しく動作しているか確認する
- [x] 不要なコードが含まれていないか( コメントやログの消し忘れに注意 )
- [x] XSS になるようなコードが含まれていないか
- [x] Pull Reuqest の内容は妥当か( 膨らみすぎてないか )

より詳しい内容は [Pull Request Policy](https://github.com/zenn-dev/zenn-vscode-extension/blob/main/docs/pull_request_policy.md) を参照してください。

2023-02-07 02:47 UTC, uttk-dev requested changes
@yo-goto 

返信が遅くなってしまいすいません🙏
色々考えましたが、実装の見直しが必要だと感じたのでコメントしました。
もし意見などがあれば遠慮無くコメントして頂ければと思います 💪
よろしくお願いします🙇‍♂️

2023-02-07 02:47 UTC, uttk-dev commented on src/commands/preview.ts
>      });
ここの処理は少し議論したいところです。

`previewCommand()` が担当する処理は Uri を `context.dispatchContentsEvent()` に渡すだけにして、Uri がプレビューできるか判定する処理は実際にプレビュー処理を実装している `src/schemas/previewPanel.ts` 内の `openPreviewPanel()` に実装してみてはいかがでしょうか？

イメージは以下のような感じ👇

```ts
// src/commands/preview.ts

/**
 * プレビューコマンドの実装
 */
export const previewCommand = (context?: AppContext) => {
  return (treeItem?: PreviewTreeItem) => {
    if (!context) {
      return vscode.window.showErrorMessage("コマンドの実行に失敗しました");
    } else if (treeItem?.canPreview === false) {
      return vscode.window.showErrorMessage("プレビューできないコンテンツです");
    }

    // コマンドパレットから実行する場合はアクティブなファイルをプレビューする
    const activeDocumentUri =
      vscode.window.activeTextEditor?.document.uri.toString();

    // TreeView から実行する場合は選択された TreeItem が対応するファイルをプレビューする
    const treeItemContentUri = treeItem?.contentUri?.toString();

    // プレビューするコンテンツの Uri 文字列
    const previewContentUri = treeItemContentUri || activeDocumentUri;

    if (!previewContentUri) {
      return vscode.window.showErrorMessage(
        "プレビューできるコンテンツがありませんでした。TreeViewからプレビューするコンテンツを選択するか、Zennリポジトリ内のarticlesフォルダまたはbooksフォルダにあるマークダウンファイルを開いた状態でコマンドを実行してください。"
      );
    }

    // TreeView からのボタンクリック
    return context.dispatchContentsEvent({
      type: "open-preview-panel",
      payload: { path: previewContentUri },
    });
  };
};
```
```ts
// src/schemas/previewPanel.ts

// ...

/**
 * プレビューパネルを表示する
 */
export const openPreviewPanel = async (context: AppContext, path: string) => {
  const uri = toVSCodeUri(path);

  // Uri からコンテンツ種別文字列を取得する
  const type = context.getContentsType(uri);

  // プレビューできるコンテンツ種別
  const canPreviewContentsType: ContentsType[] = [
    "article",
    "book",
    "bookChapter",
  ];

  // ここでプレビューできる Uri か判定する
  if (!type || !canPreviewContentsType.includes(type)) {
    throw new ContentError("プレビューできないコンテンツです");
  }

  // ...
};

// ...
```

意図としては、

- `previewCommand()` はどこからでも実行できてしまうため、なるべくシンプルな処理をしたい
- `openPreviewPanel()` にバリデーション処理を書いておいた方が使いやすい

といった感じです。

2023-02-07 06:16 UTC, yo-goto commented
いえいえ、丁寧にありがとうございます。こちらも連投でPR作成してしまったので、お手数をおかけしました🙇‍♂️
指摘箇所の実装については後で見直してみます!

ところで今の状態のPRでも履歴がちょっと膨らんでいる感じがするのですが、指摘部分の修正後にコミット履歴のリベースをして強制プッシュなどした方がよいでしょうか?

2023-02-07 06:36 UTC, uttk-dev commented
@yo-goto 

>ところで今の状態のPRでも履歴がちょっと膨らんでいる感じがするのですが、指摘部分の修正後にコミット履歴のリベースをして強制プッシュなどした方がよいでしょうか?

いえ、この PR にそのまま修正してコミットして大丈夫です。
Git 履歴にこだわりはないので、多少履歴が膨らんでも問題ありません。
それよりは、後で修正内容を参照しやすくしておきたいです。

2023-02-07 06:39 UTC, yo-goto commented
承知しました👍

2023-02-07 10:06 UTC, yo-goto commented on src/commands/preview.ts
>      });
確かに `previewCommand()` がシンプルな方が良さそうですね。`getContentsType()` の処理でプレビュー可能かどうかを判別できるっていうのは気づいていなかったです😅

`previewPanel.ts` ファイルにプレビュー可能な Uri か判別する関数として以下のように定義するのはどうでしょうか。

```ts
// src/schemas/previewPanel.ts

// ...

/**
 * プレビュー可能な Uri か判別する
 */
export const checkUriCanPreview = (
  context: AppContext,
  uri: vscode.Uri
): boolean => {
  const type = context.getContentsType(uri);
  const canPreviewContentsType: ContentsType[] = [
    "article",
    "book",
    "bookChapter",
  ];

  if (!type || !canPreviewContentsType.includes(type)) {
    return false;
  }
  return true;
};

// ...
```

また、現在 `openPreviewPanel()` から発生した例外はどこからも補足されてないようなので、コマンド実行時になぜ失敗したかがわからないよう感じになりそうです。したがって、この関数内で try-catch して `vscode.window.showErrorMessage()` でエラーメッセージを表示させるのはどうでしょうか。

```ts
// src/schemas/previewPanel.ts

// ...

/**
 * プレビューパネルを表示する
 */
export const openPreviewPanel = async (context: AppContext, path: string) => {
  const uri = toVSCodeUri(path);

  try {
    if (!checkUriCanPreview(context, uri)) {
      throw new ContentError("プレビューできないコンテンツです");
    }

    const cacheKey = context.cache.createKey("previewPanel", uri);
    const cache = context.cache.getCache(cacheKey);
    if (cache) return cache.panel.reveal();

    const panel = createWebViewPanel();
    const content = await loadPreviewContents(context, uri, panel).catch(
      (err) => console.error(err)
    );

    if (!content) {
      panel.dispose();
      throw new ContentError("コンテンツをプレビューできませんでした");
    }

    const previewPanel = createPreviewPanel(uri, panel, content);
    registerPreviewPanel(context, previewPanel);
  } catch (error: unknown) {
    if (error instanceof ContentError) {
      return vscode.window.showErrorMessage(error.message);
    }
  }
};
```

2023-02-07 10:11 UTC, yo-goto commented on src/utils/vscodeHelpers.ts
> +
ここは修正箇所を治すと使用しなくなりそうですが、削除した方がよさそうですかね?

2023-02-07 10:25 UTC, yo-goto commented on package.json
> +        }
見直してて気づいたのですが、エディタタイトル上にプレビューボタンが表示されるための条件の絞りこみとして、プレビュー可能な Uri をチェックする関数から真偽値を取得することで、そもそもプレビュー可能なマークダウンファイルだけにボタンを表示させることができそうです。
参考: https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context

ただ、この PR で修正するとわかりづらくなりそうなので、次のPRで作成しようと思います。

2023-02-08 01:24 UTC, uttk-dev commented on src/utils/vscodeHelpers.ts
> +
@yo-goto 使用しないなら削除でいいと思います！

2023-02-08 09:45 UTC, yo-goto commented
@uttk-dev 
修正の方してみました。

2023-02-09 01:42 UTC, uttk-dev approved these changes
LGTMです！ありがとうございます！
エラーメッセージの設計については、少し見直したいので別の Issue・PR でやりたいと思います。
なので、とりあえずこの PR はマージさせて頂きますね。

2023-02-09 01:42 UTC, merged

2023-02-09 07:04 UTC, yo-goto commented
エラーメッセージについて承知しました👍
また、マージありがとうございました🙇‍♂️

p.s. 今回のリリースの宣伝も兼ねてZennの方で「VSCode Web拡張にPR出してみた」みたいな感じで体験談かつ機能紹介&簡単なレビュー記事を作成して出したいのですが作っても大丈夫でしょうか？

2023-02-10 00:31 UTC, cm-igarashi-ryosuke commented
@yo-goto もちろん、大歓迎です！楽しみにしています 😀

2023-02-10 06:50 UTC, yo-goto commented
ありがとうございます😸
実は後から記事のネタになるかなと思って開発メモとかを残しておいたので、それも使って記事を作ってみます🙋‍♂️

2023-02-10 10:14 UTC, yo-goto commented
早速つくってみました。よかったら読んでみてください👍
https://zenn.dev/estra/articles/prs-for-zenn-vscode-ext