feat: チャプターファイルをチャプター番号で並べ替え表示する機能の追加
zenn-dev/zenn-vscode-extension pull request #68
Opened 2023-02-08 21:46 UTC by yo-goto

## :bookmark_tabs: Summary

- ツリービュー内のBOOKSセクションにてチャプターファイルをチャプター番号で並べ替える機能を追加しました
- チャプター番号をチャプターファイルの表示にプレフィックスする機能を追加しました
- それぞれの機能を Zenn Preview の設定から制御できるようなオプション項目として実装しました

Resolves #67 

### :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [x] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-vscode-extension/blob/main/CONTRIBUTING.md) を読んだ
- [x] :woman_technologist: `canary` ブランチに対するプルリクエストである
- [x] 実行して正しく動作しているか確認する
- [x] 不要なコードが含まれていないか( コメントやログの消し忘れに注意 )
- [x] XSS になるようなコードが含まれていないか
- [x] Pull Reuqest の内容は妥当か( 膨らみすぎてないか )

より詳しい内容は [Pull Request Policy](https://github.com/zenn-dev/zenn-vscode-extension/blob/main/docs/pull_request_policy.md) を参照してください。

2023-02-09 10:08 UTC, yo-goto commented on package.json
> +          "markdownDescription": "ツリービューに表示されるチャプターファイルの表示にチャプター番号をプリフィクスするかどうかを制御します。"
設定項目の `zenn-preview.sortByChapterNumber` などは、コマンド名のようにケバブケースで登録すると設定画面でもケバブケースで表示されてしまうので、キャメルケースでの名前にしています。

2023-02-13 04:27 UTC, uttk-dev requested changes
@yo-goto 

便利な機能でとてもいいと思います！
実装やオプションの方針についてコメントしましたので、確認よろしくお願いします🙏

あとお願いしたいんですが、オプションのデバッグしやすいように `examples/.vscode/settings.json` を追加してもらってもいいでしょうか？ 値はデフォルト値で大丈夫です。

2023-02-13 04:35 UTC, uttk-dev commented on src/schemas/book.ts
> +  });
ついでに、`loadBook` の chapter のソート処理も修正して頂けると助かります🙏 
`999` のところを `Infinity` にする感じです。そうすることで、大きな position を設定されても設定されていない chapter を下に表示するようにできます。

```diff ts
/** 本情報を取得する */
const loadBook = async (uri: vscode.Uri): Promise<BookContent> => {
  /* --- 省略 --- */
  return {
    /* --- 省略 --- */
    chapters: getBookChapterUris(uri, files)
      .map((uri) => createBookChapterMeta(uri, chapters))
      .filter((v): v is BookChapterMeta => !!v)
      .sort((a, b) => {
        return (
-         Number(a.position === null ? 999 : a.position) -
+         Number(a.position === null ? Infinity : a.position) -
-         Number(b.position === null ? 999 : b.position)
+         Number(b.position === null ? Infinity : b.position)
        );
      }),
  };
};
```

2023-02-13 09:05 UTC, yo-goto commented
コードレビューありがとうございます!
デバッグ用のオプションについて承知しました、用意してコミットしておきます👍

2023-02-13 09:09 UTC, yo-goto commented on src/treeview/book/bookChapterTreeItem.ts
> +        return "";
確かにこの場合には除外がプリフィクスされていたほうが分かりやすいと思います。`(除外)` 表示の関連サジェストを取り込みます。

2023-02-13 09:14 UTC, yo-goto commented on src/schemas/book.ts
> +  });
> ここの処理は TreeView に依存しているため、できれば TreeView 側で解決したい処理です。
> 
> 難しく考えずに、BookChapterTreeItem をインスタンス化するときに prefix になる数値をコンストラクトに渡してみてはどうでしょうか？

いやー、そこ気づいていませんでした、簡単な手があったんですねw

> ついでに、`loadBook` の chapter のソート処理も修正して頂けると助かります🙏 `999` のところを `Infinity` にする感じです。そうすることで、大きな position を設定されても、常に position がない chapter を下に表示できます。

承知しました👍

2023-02-14 09:28 UTC, yo-goto commented
@uttk-dev 
修正の方、完了しました👍
お時間あるときにレビューをよろしくお願いします🙇‍♂️

2023-02-15 01:52 UTC, uttk-dev approved these changes
LGTMです！もろもろの対応ありがとうございました🙏

2023-02-15 01:52 UTC, merged