Refactor docs
zenn-dev/zenn-vscode-extension pull request #87
Opened 2023-02-17 10:44 UTC by yo-goto

## :bookmark_tabs: Summary

- READMEドキュメントのチャプター作成機能の箇所について記述で不足していた説明箇所を追加しました。
- それに伴い、他のテンプレート作成の説明箇所などについても詳細化しておきました。

Resolves 

## :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [x] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-vscode-extension/blob/main/CONTRIBUTING.md) を読んだ
- [x] :woman_technologist: `canary` ブランチに対するプルリクエストである
- [x] 実行して正しく動作しているか確認する
- [x] 不要なコードが含まれていないか( コメントやログの消し忘れに注意 )
- [x] XSS になるようなコードが含まれていないか
- [x] Pull Reuqest の内容は妥当か( 膨らみすぎてないか )

より詳しい内容は [Pull Request Policy](https://github.com/zenn-dev/zenn-vscode-extension/blob/main/docs/pull_request_policy.md) を参照してください。

2023-02-20 05:55 UTC, uttk-dev requested changes
@yo-goto 

LGTMです！分かりやすくなって最高です！
一点だけ修正が必要な箇所があったためコメントしました、お手数ですがご確認ください〜！

2023-02-20 05:55 UTC, uttk-dev commented on README.md
> +ツリービュー GUIDES セクションに表示されたガイド記事の一覧からボタンをクリックするか、コマンドパレットから `Zenn: Open Guide` コマンドを実行することで [Zenn.dev](https://zenn.dev/zenn) 上のガイド記事にアクセスできます。
`Zenn.dev` を `zenn.dev` にして欲しいです！
その方がドメインと同じで認識しやすいと思いました！

```suggestion
ツリービュー GUIDES セクションに表示されたガイド記事の一覧からボタンをクリックするか、コマンドパレットから `Zenn: Open Guide` コマンドを実行することで [zenn.dev](https://zenn.dev/zenn) 上のガイド記事にアクセスできます。
```

2023-02-20 11:20 UTC, yo-goto commented
後ほど修正してプッシュしておきます！

2023-02-20 11:21 UTC, yo-goto commented on README.md
> +ツリービュー GUIDES セクションに表示されたガイド記事の一覧からボタンをクリックするか、コマンドパレットから `Zenn: Open Guide` コマンドを実行することで [Zenn.dev](https://zenn.dev/zenn) 上のガイド記事にアクセスできます。
確かにです。了解しました🫡

2023-02-20 16:09 UTC, yo-goto commented
リンク名を修正しておきました👍

2023-02-21 03:59 UTC, uttk-dev approved these changes
LGTMです！ありがとうございます！

2023-02-21 03:59 UTC, merged